name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install and run Pester
      run: |
        Install-Module Pester -Force
        Invoke-Pester .\tests -ExcludeTag Integration -Show Fails
      shell: pwsh
